#!/usr/bin/env python3
"""
Interactive setup script for Swanson Framework.

Guides user through initial configuration.
Cross-platform compatible.
"""

import json
import sys
from pathlib import Path


def main():
    """Run interactive setup."""
    print("=== Swanson Framework Setup ===\n")
    print("This script will help you configure Swanson.\n")

    # Check if already configured
    env_file = Path(".env")
    config_file = Path("config.json")

    if env_file.exists() or config_file.exists():
        print("Configuration already exists:")
        if env_file.exists():
            print("  - .env file found")
        if config_file.exists():
            print("  - config.json file found")

        response = input("\nOverwrite existing configuration? [y/N]: ")
        if response.lower() != "y":
            print("Setup cancelled.")
            sys.exit(0)

    # Get API key
    print("\n1. Anthropic API Key")
    print("   Get your API key from: https://console.anthropic.com/settings/keys")
    print("   Your key should start with 'sk-ant-'")

    while True:
        api_key = input("\n   Enter your API key: ").strip()

        if not api_key:
            print("   Error: API key cannot be empty")
            continue

        if not api_key.startswith("sk-ant-"):
            print("   Warning: Key doesn't start with 'sk-ant-'")
            response = input("   Continue anyway? [y/N]: ")
            if response.lower() != "y":
                continue

        break

    # Choose configuration method
    print("\n2. Configuration Method")
    print("   a) .env file (recommended)")
    print("   b) config.json file")

    while True:
        method = input("\n   Choose method [a/b]: ").strip().lower()
        if method in ["a", "b"]:
            break
        print("   Please choose 'a' or 'b'")

    # Write configuration
    if method == "a":
        # Write .env file
        with open(".env", "w", encoding="utf-8") as f:
            f.write("# Swanson Framework Configuration\n")
            f.write("# Generated by setup.py\n\n")
            f.write(f"ANTHROPIC_API_KEY={api_key}\n")

        print("\n✓ Created .env file")

    else:
        # Write config.json file
        config_data = {
            "anthropic_api_key": api_key,
            "model": "sonnet",
        }

        with open("config.json", "w", encoding="utf-8") as f:
            json.dump(config_data, f, indent=2)

        print("\n✓ Created config.json")

    # Validate configuration
    print("\n3. Validating configuration...")

    try:
        from src.swanson.config import config

        config.validate()
        print("✓ Configuration is valid")

    except ImportError:
        print("✓ Configuration created (validation requires swanson installation)")
    except Exception as e:
        print(f"✗ Configuration error: {e}")
        sys.exit(1)

    # Next steps
    print("\n=== Setup Complete ===\n")
    print("Next steps:")
    print("1. Initialize a project: python init.py")
    print("2. Add PRDs to prds/ directory")
    print("3. Run: python src/swanson/loop.py")
    print("\nSee README.md for detailed usage instructions.")


if __name__ == "__main__":
    main()
